import EGFetch from './fetch';
import Ajax from './ajax';
import axios from './axios';
import request from './request';
import { getStyle, getStyles } from './style';
import {
  copy,
  extend,
  pageData,
  tryGet,
  guid,
  encrypt,
  decrypt,
  formatDataSource,
  getQueryString,
  downLoadFile,
  downLoadUrl,
  replaceFun,
  getChinese,
  getEnglish,
  verifyAdmin,
  getBase64,
  fileString,
  getPageSize,
  getConfig,
  inputValidator,
  chineseValidator,
  englishValidator,
  getStrByWith,
  getLen,
  subStr,
  judgePurity,
  loadJS,
  getParentKey,
  generateList,
  createAssociationTree,
  dealError,
  microAppHistory,
} from './util';

export {
  Ajax,
  EGFetch,
  getStyle,
  getStyles,
  copy,
  extend,
  pageData,
  tryGet,
  guid,
  encrypt,
  decrypt,
  formatDataSource,
  getQueryString,
  downLoadFile,
  downLoadUrl,
  replaceFun,
  getChinese,
  getEnglish,
  verifyAdmin,
  getBase64,
  fileString,
  getPageSize,
  getConfig,
  inputValidator,
  chineseValidator,
  englishValidator,
  getStrByWith,
  getLen,
  subStr,
  judgePurity,
  loadJS,
  getParentKey,
  generateList,
  createAssociationTree,
  dealError,
  axios,
  request,
  microAppHistory
};
